repos:
- "https://github.com/jazzband/django-redshift-backend"
ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit.com hooks
  
      for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
