# Generated by Django 3.2.12 on 2022-02-13 21:03

from django.db import migrations, models
import django.db.models.deletion
import django_redshift_backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField()),
                ('text', models.TextField()),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='TestParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestReferencedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestModelWithMetaKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.testreferencedmodel')),
            ],
            options={
                'ordering': [django_redshift_backend.SortKey('created_at'), django_redshift_backend.SortKey('-id')],
            },
        ),
        migrations.CreateModel(
            name='TestChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.testparentmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='testmodelwithmetakeys',
            index=django_redshift_backend.DistKey(fields=['fk'], name='testapp_tes_fk_id_cd99f5_idx'),
        ),
    ]
