name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        linter:
          - flake8
          - readme

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U tox
      - run: tox -e ${{ matrix.linter }}
